addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.8.5")
//addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.4.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.2.0")
addSbtPlugin("me.lessis" % "bintray-sbt" % "0.3.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header" % "1.6.0")
