package io.rdbc.sapi

import io.rdbc.ImmutSeq

/** Specification of columns that generate keys */
sealed trait KeyColumns

object KeyColumns {
  /** Return keys from the column names given */
  def named(cols: String*): KeyColumns.Named = KeyColumns.Named(cols.toVector)

  /** Return all keys */
  case object All extends KeyColumns

  /** Don't return any keys */
  case object None extends KeyColumns

  /** Return keys from the column names given */
  final case class Named(cols: ImmutSeq[String]) extends KeyColumns

}

object StatementOptions {

  /** Default statement options */
  val Default: StatementOptions = StatementOptions(generatedKeyCols = KeyColumns.None)

  /** Options that make statement return all generated keys */
  val ReturnGenKeys: StatementOptions = Default.copy(generatedKeyCols = KeyColumns.All)
}

/**
  * Statement options.
  *
  * @param generatedKeyCols says what keys generated by the database should be returned
  */
final case class StatementOptions(generatedKeyCols: KeyColumns)
